Make clcadmin-assume-system-creds test for 0 keys
This adds a specific check and error message for the case where
eucalyptus/admin has no access keys.

Fixes EUCA-11780

diff --git a/tools/clcadmin-assume-system-credentials b/tools/clcadmin-assume-system-credentials
--- a/tools/clcadmin-assume-system-credentials
+++ b/tools/clcadmin-assume-system-credentials
@@ -1,6 +1,6 @@
 #!/bin/bash -e
 #
-# Copyright 2015 Eucalyptus Systems, Inc.
+# Copyright (c) 2015-2017 Hewlett Packard Enterprise Development LP
 #
 # Redistribution and use of this software in source and binary forms,
 # with or without modification, are permitted provided that the following
@@ -26,7 +26,10 @@
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 KEYSTORE_PATH="$EUCALYPTUS/var/lib/eucalyptus/keys/euca.p12"
-HOST=127.0.0.1
+DB_HOST=127.0.0.1
+
+KEY_QUERY="FROM eucalyptus_auth.auth_access_key k JOIN eucalyptus_auth.auth_user u ON k.auth_access_key_owning_user=u.id JOIN eucalyptus_auth.auth_group_has_users gu ON u.id=gu.auth_user_id JOIN eucalyptus_auth.auth_group g ON gu.auth_group_id=g.id JOIN eucalyptus_auth.auth_account a ON g.auth_group_owning_account=a.id WHERE a.auth_account_name='eucalyptus' AND g.auth_group_name='_admin' AND k.auth_access_key_active=TRUE"
+KEY_COLUMNS="k.auth_access_key_query_id, k.auth_access_key_key"
 
 if [ "$#" -ne 0 ]; then
     fmt -u >&2 <<EOF
@@ -44,12 +47,16 @@ elif [ $(id -u) -ne 0 ]; then
 fi
 
 export PGPASSWORD=$(echo -n eucalyptus | openssl dgst -sha256 -sign <(openssl pkcs12 -in "$KEYSTORE_PATH" -passin pass:eucalyptus -nodes -nomacver | sed -n '/friendlyName: eucalyptus/,/friendlyName:/{/-----BEGIN.*PRIVATE/,/-----END.*PRIVATE/p}') | sha256sum | sed 's/ .*//')
-creds=$(psql -Aqt -F : -h $HOST -p 8777 -U eucalyptus -w eucalyptus_shared -c "SELECT k.auth_access_key_query_id, k.auth_access_key_key FROM eucalyptus_auth.auth_access_key k JOIN eucalyptus_auth.auth_user u ON k.auth_access_key_owning_user=u.id JOIN eucalyptus_auth.auth_group_has_users gu ON u.id=gu.auth_user_id JOIN eucalyptus_auth.auth_group g ON gu.auth_group_id=g.id JOIN eucalyptus_auth.auth_account a ON g.auth_group_owning_account=a.id WHERE a.auth_account_name='eucalyptus' AND g.auth_group_name='_admin' AND k.auth_access_key_active=TRUE LIMIT 1")
+n_creds=$(psql -Aqt -F : -h $DB_HOST -p 8777 -U eucalyptus -w eucalyptus_shared -c "SELECT COUNT(*)     $KEY_QUERY")
+creds=$(  psql -Aqt -F : -h $DB_HOST -p 8777 -U eucalyptus -w eucalyptus_shared -c "SELECT $KEY_COLUMNS $KEY_QUERY LIMIT 1")
 key_id=$(echo $creds | cut -d: -f1)
 secret_key=$(echo $creds | cut -d: -f2)
 
-if [ -z "$key_id" ] || [ -z "$secret_key" ]; then
-    echo "$0: failed to obtain access keys; ensure eucalyptus-cloud has finished starting" >&2
+if [ "$n_creds" -eq 0 ]; then
+    echo "$(basename $0): eucalyptus admin has no access keys; please restart eucalyptus-cloud and try again" >&2
+    exit 1
+elif [ -z "$key_id" ] || [ -z "$secret_key" ]; then
+    echo "$(basename $0): failed to obtain access keys; ensure eucalyptus-cloud has finished starting" >&2
     exit 1
 fi
 
