only run eucanetd if eucanetd is installed

diff --git a/tools/eucalyptus-nc.in b/tools/eucalyptus-nc.in
--- a/tools/eucalyptus-nc.in
+++ b/tools/eucalyptus-nc.in
@@ -210,10 +210,12 @@ do_start() {
 	# let's be sure we have the right port for NC and CC
 	create_httpd_config
 
-        if ! $EUCALYPTUS/usr/sbin/eucanetd ; then
-            echo
-            echo "Failed to start the eucanetd"
-        fi
+	if [ -x $EUCALYPTUS/usr/sbin/eucanetd ]; then
+            if ! $EUCALYPTUS/usr/sbin/eucanetd ; then
+		echo
+		echo "Failed to start the eucanetd"
+            fi
+	fi
 
 	if ! $HTTPD -f $EUCALYPTUS/etc/eucalyptus/httpd-nc.conf ; then
 		echo
