We need to remove the semaphore on start/stop of the CC/NC. Added upgrade path of the configuration file for RPMs.

diff --git a/tools/euca_conf b/tools/euca_conf
--- a/tools/euca_conf
+++ b/tools/euca_conf
@@ -20,9 +20,15 @@ NODEMODE=""
 CLUSNAME=""
 NEWCLUS=""
 CLUSMODE=""
+UPGRADE_CONF=""
 
 usage () {
 	echo "$0 [options] [<file>]"
+	echo
+	echo "Modify Eucalyptus configuration file. [<file>] is the"
+	echo "configuration file to be modified: if it's now specified"
+	echo "it will searched in $EUCALYPUTS/etc/eucalyptus"
+	echo
 	echo
 	echo "   -help                       this message"
 	echo "   -d <dir>                    point EUCALYPTUS to <dir>"
@@ -56,13 +62,13 @@ change_var_value () {
 # comment lines matching $2 ($1 is the file)
 comment () {
 	cp $1 /tmp/euca-tmp.$$
-	sed "s<[[:blank:]]*\(${2}.*\)<#\1<" /tmp/euca-tmp.$$ > $1
+	sed "s<^[[:blank:]]*\(${2}.*\)<#\1<" /tmp/euca-tmp.$$ > $1
 	rm -f /tmp/euca-tmp.$$
 }
 # comment lines matching $2 ($1 is the file)
 uncomment () {
 	cp $1 /tmp/euca-tmp.$$
-	sed "s<[#[:blank:]]*\(${2}.*\)<\1<" /tmp/euca-tmp.$$ > $1
+	sed "s<^[#[:blank:]]*\(${2}.*\)<\1<" /tmp/euca-tmp.$$ > $1
 	rm -f /tmp/euca-tmp.$$
 }
 
@@ -108,6 +114,16 @@ while [ $# -gt 0 ]; do
 			exit 1
 		fi
 		NAME="$2"
+		shift; shift
+		continue
+	fi		
+	if [ "$1" = "-upgrade-conf" ]; then
+		# hidden options to upgrade from an older version
+		UPGRADE_CONF="$2"
+		if [ ! -e "$UPGRADE_CONF" ]; then
+			echo "Cannot read $UPGRADE_CONF"
+			exit 1
+		fi
 		shift; shift
 		continue
 	fi		
@@ -166,20 +182,12 @@ while [ $# -gt 0 ]; do
 		continue
 	fi
 	if [ "$1" = "-addnode" ]; then 
-	    if [ $# -lt 2 ]; then
-		echo "Requires the hostname of the node to add"
-		exit 1
-	    fi
 	    NEWNODE="$2"
 	    NODEMODE="ADD"
 	    shift; shift
 	    continue
 	fi
 	if [ "$1" = "-delnode" ]; then 
-	    if [ $# -lt 2 ]; then
-		echo "Requires the hostname of the node to delete"
-		exit 1
-	    fi
 	    NEWNODE="$2"
 	    NODEMODE="REM"
 	    shift; shift
@@ -187,13 +195,13 @@ while [ $# -gt 0 ]; do
 	fi
 	if [ "$1" = "-addcluster" ]; then
 	    if [ $# -lt 3 ]; then
-		echo "Requires the cluster nice name, hostname and admin access key"
+		echo "Requires the cluster nice name and CC hostname"
 		exit 1
 	    fi
 	    CLUSNAME="$2"
 	    NEWCLUS="$3"
 	    CLUSMODE="ADD"
-	    shift; shift; shift; shift
+	    shift; shift; shift
 	    continue
 	fi
 	usage 
@@ -203,7 +211,7 @@ done
 # some basic check
 if [ -z "${FILE}" -o ! -f "${FILE}" ]; then
 	echo "Is <$FILE> a valid eucalyptus configuration file?"
-	exit 1
+	exit 
 fi
 
 # let's change the value
@@ -246,18 +254,51 @@ if [ -n "$NAME" ]; then
 	VALUE=`cat $FILE |grep $NAME|cut -f 2 -d =|tr  '"' ' '`
 	echo $VALUE
 fi
-if [ -n "$NEWCLUS" ]; then
 
-    if [ -f "$FILE" ]; then
+# modify the current conf file based on an older configuration
+if [ -n "$UPGRADE_CONF" ]; then
+	VARS="EUCA_USER ENABLE_WS_SECURITY LOGLEVEL CLOUD_PORT CLOUD_SSL_PORT CC_PORT SCHEDPOLICY NODES NC_SERVICE NC_PORT HYPERVISOR MAX_MEM MAX_CORES INSTANCE_PATH VNET_INTERFACE VNET_BRIDGE VNET_DHCPDAEMON"
+	VNET_VARS="VNET_MODE VNET_SUBNET VNET_NETMASK VNET_DNS VNET_ADDRSPERNET VNET_PUBLICIPS VNET_BROADCAST VNET_ROUTER VNET_MACMAP"
+	
+	# source the old config
+	. $UPGRADE_CONF
+
+	# let's start from no network
+	for x in $VNET_VARS ; do
+		comment $FILE $x
+	done
+		
+	# modified the defined variables
+	for x in $VARS ; do
+		y="$(echo \$${x})"
+		eval y="$y"
+		if [ -z "$y" ]; then
+			# we just leave NODES uncomment even if it's empty
+			if [ "$x" != "NODES" ]; then
+				comment $FILE $x
+			fi
+		else
+			uncomment $FILE $x
+			change_var_value $FILE $x "${y}"
+		fi
+	done
+	# and add the network variables
+	echo >> $FILE
+	echo "# network configuration from the old configuration file" >> $FILE
+	for x in $VNET_VARS ; do
+		y="$(echo \$${x})"
+		eval y="$y"
+		if [ -n "$y" ]; then
+			echo "$x=\"${y}\"" >> $FILE
+		fi
+	done
+fi
+
+# adding a new cluster
+if [ -n "$NEWCLUS" ]; then
 	. $FILE
-    else
-	echo "ERROR: cannot find file '$EUCALYPTUS/etc/eucalyptus.conf'. Is your EUCALYPTUS enviroment variable set?"
-	exit 1
-    fi
     
     if [ -d "$EUCALYPTUS/var/lib/eucalyptus/db/" ]; then
-	DBDIR="$EUCALYPTUS/var/lib/eucalyptus/db/"
-    elif [ -d "$EUCALYPTUS/var/lib/eucalyptus/db/" ]; then
 	DBDIR="$EUCALYPTUS/var/lib/eucalyptus/db/"
     else
 	echo "ERROR: cannot locate eucalyptus database, try logging in through the admin web interface"
@@ -291,16 +332,10 @@ if [ -n "$NEWCLUS" ]; then
     echo "New cluster '${CLUSNAME}' on host '${NEWCLUS}' successfully added."
 fi
 
+# adding a new node
 if [ -n "$NEWNODE" ]; then
-
-    if [ -f "$FILE" ]; then
-	. $FILE
-    else
-	echo "ERROR: cannot find file '$EUCALYPTUS/etc/eucalyptus.conf'. Is your EUCALYPTUS enviroment variable set?"
-	exit 1
-    fi
+    . $FILE
     TMPFILE="$FILE.$$"
-    
     
     if [ "$NODEMODE" = "ADD" ]; then
 	EUCA_HOME=`su - -c 'echo $HOME' $EUCA_USER`
@@ -327,8 +362,6 @@ if [ -n "$NEWNODE" ]; then
     fi
     
     if [ -d "$EUCALYPTUS/var/lib/eucalyptus/keys/" ]; then
-	KEYDIR="$EUCALYPTUS/var/lib/eucalyptus/keys/"
-    elif [ -d "$EUCALYPTUS/var/lib/eucalyptus/keys/" ]; then
 	KEYDIR="$EUCALYPTUS/var/lib/eucalyptus/keys/"
     else
 	echo "ERROR: cannot locate eucalyptus database, try logging in through the admin web interface"
