added -norsync option for distro with no root user

diff --git a/tools/euca_conf b/tools/euca_conf
--- a/tools/euca_conf
+++ b/tools/euca_conf
@@ -34,6 +34,7 @@ usage () {
 	echo "   -d <dir>                    point EUCALYPTUS to <dir>"
 	echo "   -addnode <hostname>         add new node to EUCALYPTUS"
 	echo "   -synckeys                   sync the keys with the nodes"
+	echo "   -norsync                    don't use rsync (ie remote node have no root)"
 	echo "   -delnode <hostname>         remove node from EUCALYPTUS"
 	echo "   -addcluster <clusname> <hostname> add new cluster to EUCALYPTUS"
 #	echo "   -delcluster <clusname> <hostname> remove cluster from EUCALYPTUS"
@@ -104,6 +105,11 @@ while [ $# -gt 0 ]; do
 
 	if [ "$1" = "-synckeys" -o "$1" = "-synckey" ]; then 
 	    NODEMODE="SYNC"
+	    shift
+	    continue
+	fi
+	if [ "$1" = "-norsync" ]; then 
+	    RSYNC=""
 	    shift
 	    continue
 	fi
@@ -536,6 +542,35 @@ if [ -n "$NODEMODE" ]; then
 		fi
 	fi
 
+	# check we have a valid command
+	if [ "$NODEMODE" != "ADD" -a "$NODEMODE" != "REM" ]; then
+		echo "ERROR: unknown mode '$NODEMODE', don't know what to do"
+		exit 1
+	fi
+
+	# we need the keys
+	if [ -d "$EUCALYPTUS/var/lib/eucalyptus/keys/" ]; then
+		KEYDIR="$EUCALYPTUS/var/lib/eucalyptus/keys/"
+	elif [ "$NODEMODE" = "ADD" ]; then
+		echo "ERROR: cannot find keys, did you configured eucalyptus?"
+		exit 1
+	fi
+
+	# we may need the pub key to connect to remote hosts
+	EUCA_HOME=`su - -c 'echo $HOME' $EUCA_USER`
+	if [ -f "${EUCA_HOME}/.ssh/id_rsa.pub" ]; then
+		SSHKEY=`cat ${EUCA_HOME}/.ssh/id_rsa.pub`
+	else
+		SSHKEY=""
+	fi
+
+	# warn the user on where we expect the keys to be
+	if [ "$NODEMODE" = "ADD" ]; then 
+		echo
+		echo "We expect all nodes to have eucalyptus installed in $EUCALYPTUS."
+		echo
+	fi
+
 	# adding (or removing) nodes
 	for NEWNODE in ${NEWNODES} ; do
 		# remove is simpler: just remove the node name
@@ -550,42 +585,42 @@ if [ -n "$NODEMODE" ]; then
 			continue
 		fi
 	
-		# let's be sure the mode is now ADD
-		if [ "$NODEMODE" != "ADD" ]; then
-			echo "ERROR: unknown mode '$NODEMODE', don't know what to do"
-			exit 1
-		fi
-		echo
- 
-		# we need the keys
-		if [ -d "$EUCALYPTUS/var/lib/eucalyptus/keys/" ]; then
-			KEYDIR="$EUCALYPTUS/var/lib/eucalyptus/keys/"
-		else
-			echo "ERROR: cannot find keys, did you configured eucalyptus?"
-			exit 1
-		fi
-
 		# we try rsync first then scp
+		DONE="N"
 		if [ -n "$RSYNC" ]; then
 			echo "Using rsync to sync keys with node \"${NEWNODE}\" (user \"${EUCA_USER}\")"
-			$RSYNC -az ${KEYDIR}/*-cert.pem ${KEYDIR}/node-pk.pem ${EUCA_USER}@${NEWNODE}:${KEYDIR}/ > /dev/null
-		elif [ -n "$SCP" ]; then
+			if $RSYNC -az ${KEYDIR}/*-cert.pem ${KEYDIR}/node-pk.pem ${EUCA_USER}@${NEWNODE}:${KEYDIR}/ > /dev/null ; then
+				DONE="Y"
+			fi
+		fi
+		if [ -n "$SCP" -a "$DONE" = "N" ]; then
 			echo "Using scp to sync keys with node \"${NEWNODE}\" (user \"${EUCA_USER}\")"
-			sudo -u ${EUCA_USER} $SCP ${KEYDIR}/*-cert.pem ${KEYDIR}/node-pk.pem ${EUCA_USER}@${NEWNODE}:${KEYDIR} > /dev/null
-		else
-			echo "Couldn't find neither rsync nor scp!"
-			exit 1
+			if sudo -u ${EUCA_USER} $SCP ${KEYDIR}/*-cert.pem ${KEYDIR}/node-pk.pem ${EUCA_USER}@${NEWNODE}:${KEYDIR} > /dev/null ; then
+				DONE="Y"
+			fi
 		fi
 
-		# let's be sure we didn't fail
-		if [ "$?" != "0" ]; then
-			echo "ERROR: could not synchronize keys. Node ${NEWNODE} may not be available."
+		# let's warn user if we didn't sync
+		if [ "$DONE" = "N" ]; then
+			echo "Warning: could not synchronize keys with $NEWNODE!"
+			echo "and the node will not be added to the node list"
+			if [ "$SSHKEY" = "" ]; then
+				echo "User $EUCA_USER may have to run ssh-keygen!"
+			else
+				echo "To setup passwordless login to the nodes as user $EUCA_USER, you can"
+				echo "run the following commands on node $NEWNODE:"
+				echo "sudo tee ~${EUCA_USER}/.ssh/authorized_keys > /dev/null <<EOT"
+				echo "$SSHKEY"
+				echo "EOT"
+				echo ""
+				echo "Be sure that authorized_keys is not group/world readable or writable"
+			fi
 			continue
 		fi
  
 		# NODES list
 		if ! echo "${NODES}"|grep "${NEWNODE}" > /dev/null ; then
-			# node is not preset: we need to add it
+			# node is not present: we need to add it
 			NODES="${NODES} $NEWNODE"
 			change_var_value $FILE NODES "${NODES}"
 		fi
