Few details/minor bugs: 	- the printout was cluttered when ip_forward needed to be enabled 	- euca-sync-key is now deprecated: it calls euca_conf 	- added -synckey to euca_conf to sync the keys 	- euca_conf -delnode claimed success no matter what 	- euca_conf -addnode was waiting for input (bad for scripting) and 	  printing ubuntu specific instructions 	- euca_conf -addnode can now add multiple nodes 	- in the init.d scripts commented out the setuid parts

diff --git a/tools/euca_conf b/tools/euca_conf
--- a/tools/euca_conf
+++ b/tools/euca_conf
@@ -15,7 +15,7 @@ EUCA_USER=""
 HYPERVISOR=""
 DHCPD=""
 DHCP_USER=""
-NEWNODE=""
+NEWNODES=""
 NODEMODE=""
 CLUSNAME=""
 NEWCLUS=""
@@ -33,6 +33,7 @@ usage () {
 	echo "   -help                       this message"
 	echo "   -d <dir>                    point EUCALYPTUS to <dir>"
 	echo "   -addnode <hostname>         add new node to EUCALYPTUS"
+	echo "   -synckeys                   sync the keys with the nodes"
 	echo "   -delnode <hostname>         remove node from EUCALYPTUS"
 	echo "   -addcluster <clusname> <hostname> add new cluster to EUCALYPTUS"
 #	echo "   -delcluster <clusname> <hostname> remove cluster from EUCALYPTUS"
@@ -81,6 +82,11 @@ while [ $# -gt 0 ]; do
 		exit 1
 	fi
 
+	if [ "$1" = "-synckeys" ]; then 
+	    NODEMODE="SYNC"
+	    shift
+	    continue
+	fi
 	if [ $# -eq 1 ]; then
 		# we dont have options with no argument, so it has to be
 		# the file
@@ -186,13 +192,13 @@ while [ $# -gt 0 ]; do
 		continue
 	fi
 	if [ "$1" = "-addnode" ]; then 
-	    NEWNODE="$2"
+	    NEWNODES="${2}"
 	    NODEMODE="ADD"
 	    shift; shift
 	    continue
 	fi
 	if [ "$1" = "-delnode" ]; then 
-	    NEWNODE="$2"
+	    NEWNODES="${2}"
 	    NODEMODE="REM"
 	    shift; shift
 	    continue
@@ -217,6 +223,9 @@ if [ -z "${FILE}" -o ! -f "${FILE}" ]; then
 	usage
 	exit 
 fi
+
+# let's keep a copy of the original file before starting
+cp $FILE $FILE.bak
 
 # let's change the value
 if [ -n "$EUCALYPTUS" ]; then
@@ -336,78 +345,62 @@ if [ -n "$NEWCLUS" ]; then
     echo "New cluster '${CLUSNAME}' on host '${NEWCLUS}' successfully added."
 fi
 
-# adding a new node
-if [ -n "$NEWNODE" ]; then
-    . $FILE
-    TMPFILE="$FILE.$$"
-    
-    if [ "$NODEMODE" = "ADD" ]; then
-	EUCA_HOME=`su - -c 'echo $HOME' $EUCA_USER`
-	echo $EUCA_HOME
-	if [ -f "${EUCA_HOME}/.ssh/id_rsa.pub" ]; then
-	    SSHKEY=`cat ${EUCA_HOME}/.ssh/id_rsa.pub`
-        else
-	    SSHKEY=""
-        fi
-	
-	if [ "$SSHKEY" = "" ]; then
-	    echo "WARNING: cannot read ssh key ~${EUCA_USER}/.ssh/id_rsa.pub, syncronization will ask you to enter a password."
-	else
-	    echo "First, please run the following commands on '$NEWNODE':"
-	    echo ""
-	    echo "sudo apt-get install eucalyptus-nc"
-	    echo "sudo tee ~${EUCA_USER}/.ssh/authorized_keys > /dev/null <<EOT"
-	    echo "$SSHKEY"
-	    echo "EOT"
-	    echo ""
-	    echo "hit return to continue"
-	    read
-	fi
-    fi
-    
-    if [ -d "$EUCALYPTUS/var/lib/eucalyptus/keys/" ]; then
-	KEYDIR="$EUCALYPTUS/var/lib/eucalyptus/keys/"
-    else
-	echo "ERROR: cannot locate eucalyptus database, try logging in through the admin web interface"
-	exit 1
-    fi
-    
-    if [ "$NODEMODE" = "ADD" ]; then
-	sudo -u $EUCA_USER scp ${KEYDIR}/* ${EUCA_USER}@${NEWNODE}:${KEYDIR}
-	if [ "$?" != "0" ]; then
-	    echo "ERROR: could not syncronize keys, check authorized_keys on ${NEWNODE}, then run this command again."
-	    exit 1
-	fi
-    fi
-    
-    export NODES=`echo $NODES | sed "s/ *$NEWNODE *//g"`
+# operations on the nodes?
+if [ -n "$NODEMODE" ]; then
+	. $FILE
 
-# sed in new value
-    if [ "$NODEMODE" = "ADD" ]; then
-	cat $FILE | sed "/NODES=/s/NODES=.*/NODES=\"$NODES $NEWNODE\"/" > $TMPFILE
-    elif [ "$NODEMODE" = "REM" ]; then
-	cat $FILE | sed "/NODES=/s/ *$NEWNODE *//g" > $TMPFILE
-    else
-	echo "ERROR: unknown mode '$NODEMODE', don't know what to do"
-	exit 1
-    fi    
-    
-    if [ ! -s "$TMPFILE" ]; then
-	echo "ERROR: failed to add node to $FILE"
-	exit 1
-    fi
-    
-# create backup
-    cp $FILE $FILE.bak && cp $TMPFILE $FILE
-    if [ "$?" != "0" ]; then
-	echo "ERROR: could not install new conf file"
-	exit 1
-    fi
-    
-    rm $TMPFILE
-    if [ "$NODEMODE" = "ADD" ]; then
-	echo "SUCCESS: added node '$NEWNODE' to '$FILE'"
-    elif [ "$NODEMODE" = "REM" ]; then
-	echo "SUCCESS: removed node '$NEWNODE' from '$FILE'"
-    fi
+	# for synckey we fake addnodes
+	if [ "$NODEMODE" = "SYNC" ]; then
+		if [ -z "$NODES" ]; then
+			echo "Warning: there are no NODES configured"
+		else
+			NEWNODES="${NODES}"
+			NODEMODE="ADD"
+		fi
+	fi
 fi
+
+# adding (or removing) nodes
+for NEWNODE in ${NEWNODES} ; do
+	# remove is simpler: just remove the node name
+	if [ "$NODEMODE" = "REM" ]; then
+		if ! echo "$NODES"|grep "${NEWNODE}" > /dev/null ; then
+			echo "Node ${NEWNODE} is not known"
+			continue
+		fi
+		NODES="`echo $NODES|sed 's/${NEWNODE}//'|tr -s ' '`"
+		change_var_value $FILE NODES "${NODES}"
+		echo "SUCCESS: removed node '${NEWNODE}' from '$FILE'"
+		continue
+	fi
+	
+	# let's be sure the mode is now ADD
+	if [ "$NODEMODE" != "ADD" ]; then
+		echo "ERROR: unknown mode '$NODEMODE', don't know what to do"
+		exit 1
+	fi
+	echo
+ 
+	# we need the keys
+	if [ -d "$EUCALYPTUS/var/lib/eucalyptus/keys/" ]; then
+		KEYDIR="$EUCALYPTUS/var/lib/eucalyptus/keys/"
+	else
+		echo "ERROR: cannot find keys, did you configured eucalyptus?"
+		exit 1
+	fi
+
+	# warn the user on what we are going to do
+	echo "Using scp to sync keys with node \"${NEWNODE}\" (user \"$EUCA_USER\")"
+	sudo -u $EUCA_USER scp ${KEYDIR}/*-cert.pem ${KEYDIR}/node-pk.pem ${EUCA_USER}@${NEWNODE}:${KEYDIR}
+	if [ "$?" != "0" ]; then
+		echo "ERROR: could not synchronize keys. Node ${NEWNODE} may not be available."
+		continue
+	fi
+ 
+	# NODES list
+	if ! echo "${NODES}"|grep "${NEWNODE}" > /dev/null ; then
+		# node is not preset: we need to add it
+		NODES="${NODES} $NEWNODE"
+		change_var_value $FILE NODES "${NODES}"
+	fi
+done
diff --git a/tools/eucalyptus-cc.in b/tools/eucalyptus-cc.in
--- a/tools/eucalyptus-cc.in
+++ b/tools/eucalyptus-cc.in
@@ -42,6 +42,7 @@ fi
 PATH=/sbin:/usr/sbin:/bin:/usr/bin:$PATH
 DESC="Eucalyptus cluster controller"
 NAME=eucalyptus-cc
+EUCA_USER="eucalyptus"
 
 # honor the ENV variable if found otherwise look in root
 if [ -z "$EUCALYPTUS" ] ; then
@@ -51,6 +52,13 @@ if [ -z "$EUCALYPTUS" ] ; then
        fi   
 fi
 export EUCALYPTUS
+
+# just a quick way to check if we have the package still installed: at
+# times we can still have the init.d script
+if [ ! -x $EUCALYPTUS/usr/sbin/euca_conf ]; then
+	echo "Missing eucalyptus package?"
+	exit 1
+fi
 
 create_httpd_config() {
 	if [ -x "/opt/rocks/bin/rocks" ]; then
@@ -94,23 +102,25 @@ do_start() {
 			chown -R $EUCA_USER:$EUCA_USER $y
 		fi
 	done
-	if [ -x "$EUCALYPTUS/usr/share/eucalyptus/euca_rootwrap" ]; then
-		chown root:$EUCA_USER $EUCALYPTUS/usr/share/eucalyptus/euca_rootwrap
-		chmod 4750 $EUCALYPTUS/usr/share/eucalyptus/euca_rootwrap
-	fi
+#	if [ -x "$EUCALYPTUS/usr/share/eucalyptus/euca_rootwrap" ]; then
+#		chown root:$EUCA_USER $EUCALYPTUS/usr/share/eucalyptus/euca_rootwrap
+#		chmod 4750 $EUCALYPTUS/usr/share/eucalyptus/euca_rootwrap
+#	fi
 
 	# we need IP forwarding and we need to use iptable over the bridge
 	if [ -w /proc/sys/net/ipv4/ip_forward ]; then
 		VAL=`cat /proc/sys/net/ipv4/ip_forward`
 		if [ "$VAL" = "0" ]; then
-			echo "Enabling IP forwarding for eucalyptus."
+			echo
+			echo "Enabling IP forwarding"
 			echo -n 1 > /proc/sys/net/ipv4/ip_forward
 		fi
 	fi
 	if [ -w /proc/sys/net/bridge/bridge-nf-call-iptables ]; then
 		VAL=`cat /proc/sys/net/bridge/bridge-nf-call-iptables`
 		if [ "$VAL" = "0" ]; then
-			echo "Enabling bridge netfiltering for eucalyptus."
+			echo
+			echo "Enabling bridge netfiltering"
 			echo 1 >  /proc/sys/net/bridge/bridge-nf-call-iptables
 		fi
 	fi
diff --git a/tools/eucalyptus-cloud.in b/tools/eucalyptus-cloud.in
--- a/tools/eucalyptus-cloud.in
+++ b/tools/eucalyptus-cloud.in
@@ -49,6 +49,7 @@ DESC="Eucalyptus cloud controller"
 NAME=eucalyptus-cloud
 ANT="`which ant 2> /dev/null`"
 JAVA="`which java 2> /dev/null`"
+EUCA_USER="eucalyptus"
 
 # honor the ENV variable if found otherwise look in root
 if [ -z "$EUCALYPTUS" ] ; then
@@ -58,6 +59,13 @@ if [ -z "$EUCALYPTUS" ] ; then
        fi
 fi
 export EUCALYPTUS
+
+# just a quick way to check if we have the package still installed: at
+# times we can still have the init.d script
+if [ ! -x $EUCALYPTUS/usr/sbin/euca_conf ]; then
+	echo "Missing eucalyptus package?"
+	exit 1
+fi
 
 check_java() {
 	java_min_version="1.6.0"
diff --git a/tools/eucalyptus-nc.in b/tools/eucalyptus-nc.in
--- a/tools/eucalyptus-nc.in
+++ b/tools/eucalyptus-nc.in
@@ -44,6 +44,7 @@ DESC="Eucalyptus services"
 NAME=eucalyptus-nc
 BRCTL="`which brctl 2> /dev/null`"
 MODPROBE="`which modprobe 2> /dev/null`"
+EUCA_USER="eucalyptus"
 
 # honor the ENV variable if found otherwise look in root
 if [ -z "$EUCALYPTUS" ] ; then
@@ -53,6 +54,13 @@ if [ -z "$EUCALYPTUS" ] ; then
        fi   
 fi
 export EUCALYPTUS
+
+# just a quick way to check if we have the package still installed: at
+# times we can still have the init.d script
+if [ ! -x $EUCALYPTUS/usr/sbin/euca_conf ]; then
+	echo "Missing eucalyptus package?"
+	exit 1
+fi
 
 create_httpd_config() {
 	if [ -x "/opt/rocks/bin/rocks" ]; then
@@ -95,10 +103,10 @@ do_start() {
 			chown -R $EUCA_USER:$EUCA_USER $y
 		fi
 	done
-	if [ -x "$EUCALYPTUS/usr/share/eucalyptus/euca_rootwrap" ]; then
-		chown root:$EUCA_USER $EUCALYPTUS/usr/share/eucalyptus/euca_rootwrap
-		chmod 4750 $EUCALYPTUS/usr/share/eucalyptus/euca_rootwrap
-	fi
+#	if [ -x "$EUCALYPTUS/usr/share/eucalyptus/euca_rootwrap" ]; then
+#		chown root:$EUCA_USER $EUCALYPTUS/usr/share/eucalyptus/euca_rootwrap
+#		chmod 4750 $EUCALYPTUS/usr/share/eucalyptus/euca_rootwrap
+#	fi
 
 	# we have a program to test the hypervisor and more for the NC
 	if [ ! -x $EUCALYPTUS/usr/sbin/euca_test_nc ]; then
