Let's rely on euca_upgrade to check if upgrade is needed or not. Added check on euca_upgrade on needed executable (euca_conf).

diff --git a/tools/euca_upgrade b/tools/euca_upgrade
--- a/tools/euca_upgrade
+++ b/tools/euca_upgrade
@@ -148,6 +148,13 @@ fi
 
 # upgrade conf file (and keys backup) 
 if [ "$CONF" = "Y" ]; then
+	# we need euca_conf later (the new version)
+	if [ ! -x $NEW_EUCA/usr/sbin/euca_conf ];
+	then
+		echo "Cannot find new euca_conf!"
+		exit 1
+	fi
+
 	# backup the keys
 	if [ -d $NEW_EUCA/var/lib/eucalyptus/keys/$BCK_NAME ]; then
 		if [ "$FORCE" != "Y" ]; then
