Fix euca_conf --get-credentials (frequently calling this function would fail).

diff --git a/tools/euca_conf.in b/tools/euca_conf.in
--- a/tools/euca_conf.in
+++ b/tools/euca_conf.in
@@ -1095,7 +1095,12 @@ if [ -n "$CREDENTIALZIPFILE" ]; then
 	echo "cannot find code field in database, please go to the Eucalyptus web UI to obtain credentials."
 	exit 1
     fi
-    KEY=$(eval echo $(awk -v field=${FIELD} -F, '/INSERT INTO AUTH_USERS.*admin/ {print $field}' ${DBDIR}/* | head -n 1 | sed 's/[()]//g'))
+    VERCOL=`grep -i "CREATE .*TABLE AUTH_USERS" ${DBDIR}/* | sed 's/,/\n/g' | awk '/[Vv][Ee][Rr][Ss][Ii][Oo][Nn]/ {print NR}'`
+    if [ -z "$VERCOL" ]; then
+	echo "cannot find version field in database, please go to the Eucalyptus web UI to obtain credentials."
+	exit 1
+    fi
+    KEY=$(eval echo $(awk -v field=${FIELD} -v vercol=${VERCOL} -F, 'BEGIN { token=""; max=0; } /INSERT INTO AUTH_USERS.*admin/ { if ($vercol>max) { max=$vercol; token=$field; } } END { print token; }' ${DBDIR}/* | head -n 1 | sed 's/[()]//g'))
     if [ -z "$KEY" ]; then
 	echo "cannot find code in database, please go to the Eucalyptus web UI to obtain credentials."
 	exit 1
