fixes to run vmware broker as a separate (remote) component.

diff --git a/tools/euca_conf.in b/tools/euca_conf.in
--- a/tools/euca_conf.in
+++ b/tools/euca_conf.in
@@ -76,10 +76,11 @@ DHCP_USER=""
 BRIDGE=""
 NEWNODES=""
 NODEMODE=""
-WALRUS_MODE=""
 SYNC=""
 WALRUS=""
 WALRUS_MODE=""
+VMWAREBROKER=""
+VMWAREBROKER_MODE=""
 CLUSNAME=""
 NEWCLUS=""
 CLUSMODE=""
@@ -116,9 +117,11 @@ usage () {
 	echo "   --register-vmware                add new vmware to EUCALYPTUS"
 #	echo "   --deregister-vmware              remove vmware from EUCALYPTUS"
 	echo "   --register-walrus <host>         add walrus to EUCALYPTUS"
-	echo "   --deregister-walrus <host>       remove walrus to EUCALYPTUS"
+	echo "   --deregister-walrus <host>       remove walrus from EUCALYPTUS"
 	echo "   --register-sc <name> <host>      add storage controller"
-	echo "   --deregister-sc <host>           remove storage controller to EUCALYPTUS"
+	echo "   --deregister-sc <host>           remove storage controller from EUCALYPTUS"
+	echo "   --register-vmwarebroker <host>         add vmware broker to EUCALYPTUS"
+	echo "   --deregister-vmwarebroker <host>       remove vmware broker from EUCALYPTUS"
 	echo "   --list-walruses                  list registered walrus(es)"
 	echo "   --list-clusters                  list registered CCs"
 	echo "   --list-scs                       list registered SCs"
@@ -134,9 +137,9 @@ usage () {
 	echo "   --name <var>                     returns the value or <name>"
 	echo "   --import-conf <file>             import variables from <file> into eucalyptus.conf"
 	echo "   --setup                          perform initial setup"
-	echo "   --enable {cloud|walrus|sc}       enable service at next start"
-	echo "   --disable {cloud|walrus|sc}      disable service at next start"
-	echo "   --check {nc|cc|cloud|sc|walrus|vmware}  pre-flight checks"
+	echo "   --enable {cloud|walrus|sc|vmwarebroker}       enable service at next start"
+	echo "   --disable {cloud|walrus|sc|vmwarebroker}      disable service at next start"
+	echo "   --check {nc|cc|cloud|sc|walrus|vmware|vmwarebroker}  pre-flight checks"
 #	echo "   --sync {nc|cc|cloud|sc|walrus}   pre-flight checks"
 	echo "   --version                        eucalyptus version"
 	echo
@@ -262,6 +265,8 @@ component_sync_keys() {
 	echo "syncing sc($NAME)"
     elif [ "$COMPONENT" = "nc" ]; then
 	echo "syncing nc"
+    elif [ "$COMPONENT" = "vmwarebroker" ]; then
+	echo "syncing vmware broker"
     fi
 
 
@@ -575,6 +580,18 @@ while [ $# -gt 0 ]; do
 		shift; shift
 		continue
 	fi
+	if [ "$1" = "--register-vmwarebroker" ]; then
+		VMWAREBROKER_MODE="ADD"
+		VMWAREBROKER="$2"
+		shift; shift
+		continue
+	fi
+	if [ "$1" = "--deregister-vmwarebroker" ]; then
+		VMWAREBROKER_MODE="DEL"
+		VMWAREBROKER="$2"
+		shift; shift
+		continue
+	fi
 	if [ "$1" = "--register-sc" ]; then
 		if [ $# -lt 3 ]; then
 			echo "--register-sc requires a CC and a hostname"
@@ -609,8 +626,8 @@ while [ $# -gt 0 ]; do
 		continue
 	fi
 	if [ "$1" = "-check" -o "$1" = "--check" ]; then 
-		if [ "$2" != "cc" -a "$2" != "cloud" -a "$2" != "nc" -a "$2" != "sc" -a "$2" != "walrus" -a "$2" != "vmware" ]; then
-			echo "-check requires cc, nc, sc, walrus or cloud"
+		if [ "$2" != "cc" -a "$2" != "cloud" -a "$2" != "nc" -a "$2" != "sc" -a "$2" != "walrus" -a "$2" != "vmware" -a "$2" != "vmwarebroker" ]; then
+			echo "-check requires cc, nc, sc, walrus, vmwarebroker or cloud"
 			exit 1
 		fi
 		CHECK="$2"
@@ -618,8 +635,8 @@ while [ $# -gt 0 ]; do
 		continue
 	fi
 	if [ "$1" = "--enable" ]; then 
-		if [ "$2" != "cloud" -a "$2" != "sc" -a "$2" != "walrus" ]; then
-			echo "--enable requires cloud, sc or walrus"
+		if [ "$2" != "cloud" -a "$2" != "sc" -a "$2" != "walrus" -a "$2" != "vmwarebroker" ]; then
+			echo "--enable requires cloud, sc, vmwarebroker or walrus"
 			exit 1
 		fi
 		ENABLED="$ENABLED $2"
@@ -627,8 +644,8 @@ while [ $# -gt 0 ]; do
 		continue
 	fi
 	if [ "$1" = "--disable" ]; then 
-		if [ "$2" != "cloud" -a "$2" != "sc" -a "$2" != "walrus" ]; then
-			echo "--disable requires cloud, sc or walrus"
+		if [ "$2" != "cloud" -a "$2" != "sc" -a "$2" != "walrus" -a "$2" != "vmwarebroker" ]; then
+			echo "--disable requires cloud, sc, vmwarebroker or walrus"
 			exit 1
 		fi
 		DISABLED="$DISABLED $2"
@@ -636,8 +653,8 @@ while [ $# -gt 0 ]; do
 		continue
 	fi
 	if [ "$1" = "-sync" -o "$1" = "--sync" ]; then 
-		if [ "$2" != "cc" -a "$2" != "cloud" -a "$2" != "nc" -a "$2" != "sc" -a "$2" != "walrus" ]; then
-			echo "-sync requires cc, nc, sc, walrus or cloud"
+		if [ "$2" != "cc" -a "$2" != "cloud" -a "$2" != "nc" -a "$2" != "sc" -a "$2" != "walrus" -a "$2" != "vmwarebroker" ]; then
+			echo "-sync requires cc, nc, sc, walrus, vmwarebroker, cloud"
 			exit 1
 		fi
 		TOSYNC="$2"
@@ -1335,6 +1352,60 @@ if [ -n "$VMWARE" ]; then
 	if ! $EUCALYPTUS/usr/share/eucalyptus/euca_vmware --prompt --config $EUCALYPTUS/etc/eucalyptus/vmware_conf.xml ; then
 		exit 1
 	fi
+fi
+
+# vmware broker 
+if [ -n "$VMWAREBROKER" -o -n "$VMWAREBROKER_MODE" ]; then
+    if ! checkLocalService "CLC" ; then
+	exit 1
+    fi
+    
+    if [ "$VMWAREBROKER_MODE" = "ADD" ]; then
+	echo "Adding VMware Broker host $VMWAREBROKER"
+	if [ -d "${EUCALYPTUS}/var/lib/eucalyptus/keys/" ]; then
+	    SOURCEDIR=${EUCALYPTUS}/var/lib/eucalyptus/keys/
+	    DESTDIR=${EUCALYPTUS}/var/lib/eucalyptus/keys/
+	else
+	    echo "ERROR: cannot find key directory ($EUCALYPTUS/var/lib/eucalyptus/keys), check that your installation was successful!"
+	    exit 1
+	fi
+	
+	URL=""
+	if ! createCloudURL "Action" "RegisterVMwareBroker" "Host" "${VMWAREBROKER}" "Name" "vmwarebroker" "Port" "8773"; then
+	    exit 1
+	fi
+
+	if ! check_ws "$URL" ; then
+	    echo "ERROR: failed to register VMware Broker, please log in to the admin interface and check cloud status."
+	    exit 1
+	fi
+	
+	# check that vmware broker is at least running on the remote host
+	sleep 3
+	if ! check_heartbeat ${VMWAREBROKER} vmwarebroker ; then
+		echo "VMware Broker is not up on host ${VMWAREBROKER}: check the logs"
+	fi
+	
+	# sync the keys
+	if ! sync_keys ${SOURCEDIR} ${DESTDIR} ${VMWAREBROKER} euca.p12 ; then
+	    echo "ERROR: failed to sync keys with ${VMWAREBROKER}."
+            exit 1
+	fi
+	echo
+	echo "SUCCESS: new vmware broker on host '${VMWAREBROKER}' successfully registered."
+	
+    elif [ "$VMWAREBROKER_MODE" = "DEL" ]; then
+	URL=""
+	if ! createCloudURL "Action" "DeregisterVMwareBroker" "Name" "vmwarebroker"; then
+	    exit 1
+	fi
+	if ! check_ws "$URL" ; then
+	    echo "ERROR: failed to deregister VMware Broker, please log in to the admin interface and check cloud status."
+	    exit 1
+	fi
+        echo
+        echo "SUCCESS: VMware Broker successfully deregistered."
+    fi
 fi
 
 # operations on the nodes
