If vblade is not found we should stop.

diff --git a/tools/euca_conf.in b/tools/euca_conf.in
--- a/tools/euca_conf.in
+++ b/tools/euca_conf.in
@@ -680,7 +680,8 @@ if [ -n "$CHECK" ]; then
 			VBLADE="`which vblade 2> /dev/null`"
 			if [ -z "$VBLADE" ]; then
 				echo
-				echo "WARNING: EBS is enabled and vblade was not found"
+				echo "ERROR: EBS is enabled and vblade was not found"
+				exit 1
 			fi
 		fi
 	fi
