added 'get-credentials' option to euca_conf for app store integration

diff --git a/tools/euca_conf.in b/tools/euca_conf.in
--- a/tools/euca_conf.in
+++ b/tools/euca_conf.in
@@ -88,6 +88,7 @@ SETUP=""
 VERSION=""
 CHECK=""
 TO_BACKUP="Y"
+CREDENTIALZIPFILE=""
 SCP="`which scp 2> /dev/null`"
 RSYNC="`which rsync 2> /dev/null`"
 WGET="`which wget 2> /dev/null`"
@@ -98,7 +99,8 @@ usage () {
 	echo "where <file> is the configuration file ($FILE by default)"
 	echo "   --help                           this message"
 	echo "   -d <dir>                         point EUCALYPTUS to <dir>"
-#	echo "   --no-rsync                       don't use rsync (ie remote node have no root)"
+	echo "   --no-rsync                       don't use rsync (ie remote node have no root)"
+	echo "   --get-credentials <zipfile>      download credentials to <zipfile>"
 	echo "   --register-nodes \"host host ...\" add new nodes to EUCALYPTUS"
 	echo "   --delete-nodes \"host host ...\"   remove nodes from EUCALYPTUS"
 	echo "   --register-cluster <name> <host> add new cluster to EUCALYPTUS"
@@ -392,6 +394,11 @@ while [ $# -gt 0 ]; do
 #		CLOUD_PORT="$2"
 #		CLOUD_SSL_PORT="$3"
 		shift; shift; shift
+		continue
+	fi
+	if [ "$1" = "--get-credentials" ]; then
+	        CREDENTIALZIPFILE="${2}"
+		shift; shift;
 		continue
 	fi
 	if [ "$1" = "-addnode" -o "$1" = "--register-nodes" ]; then 
@@ -857,6 +864,38 @@ checkLocalService() {
     fi  
     return 0
 }
+
+if [ -n "$CREDENTIALZIPFILE" ]; then
+    if [ -f "$CREDENTIALZIPFILE" ]; then
+	echo "file '$CREDENTIALZIPFILE' already exists, please remove and try again"
+	exit 1
+    fi
+    if ! checkLocalService "CLC" ; then
+	exit 1
+    fi
+
+    if [ -d "$EUCALYPTUS/var/lib/eucalyptus/db/" ]; then
+	DBDIR="$EUCALYPTUS/var/lib/eucalyptus/db/"
+    else
+	echo "ERROR: cannot locate eucalyptus database, try logging in through the admin web interface."
+        exit 1
+    fi
+    FIELD=`grep -i "CREATE .*TABLE USERS" ${DBDIR}/* | sed 's/,/\n/g' | awk '/[Uu][Ss][Ee][Rr]_[Cc][Ee][Rr][Tt][Ii][Ff][Ii][Cc][Aa][Tt][Ee]_[Cc][Oo][Dd][Ee]/ {print NR}'`
+    if [ -z "$FIELD" ]; then
+	echo "cannot find code field in database, please go to the Eucalyptus web UI to obtain credentials."
+	exit 1
+    fi
+    KEY=$(eval echo $(awk -v field=${FIELD} -F, '/INSERT INTO USERS.*admin/ {print $field}' ${DBDIR}/* | head -n 1))
+    if [ -z "$KEY" ]; then
+	echo "cannot find code in database, please go to the Eucalyptus web UI to obtain credentials."
+	exit 1
+    fi
+    CMD="$WGET --no-check-certificate \"https://localhost:8443/getX509?user=admin&code=$KEY\" -O $CREDENTIALZIPFILE"
+    if ! eval $CMD ; then
+	echo "failed to obtain credentals, please try again or go to the Eucalytpus web UI."
+	exit 1
+    fi
+fi
 
 # adding a new cluster
 if [ -n "$CLUSNAME" ]; then
