merge eee-tng tools

diff --git a/tools/eucalyptus-nc.in b/tools/eucalyptus-nc.in
--- a/tools/eucalyptus-nc.in
+++ b/tools/eucalyptus-nc.in
@@ -210,6 +210,11 @@ do_start() {
 	# let's be sure we have the right port for NC and CC
 	create_httpd_config
 
+        if ! $EUCALYPTUS/usr/sbin/eucanetd ; then
+            echo
+            echo "Failed to start the eucanetd"
+        fi
+
 	if ! $HTTPD -f $EUCALYPTUS/etc/eucalyptus/httpd-nc.conf ; then
 		echo
 		echo "Failed to start the NC!"
@@ -230,6 +235,12 @@ do_status() {
 }
 
 do_stop() {
+	netpid="$EUCALYPTUS/var/run/eucalyptus/eucanetd.pid"
+        if [ -f "$netpid" ]; then
+            kill `cat $netpid` >/dev/null 2>&1
+            rm -f $netpid
+        fi
+
 	pidfile=$EUCALYPTUS/var/run/eucalyptus/eucalyptus-nc.pid
 
 	# let's be sure we are killing the right process
